import React from 'react';
export const franchiseDetails = () => <div>franchise distinct</div>;
export const franchise_detail_0 = (p:any)=> <div>franchise 0 royalty 6%</div>;
export const franchise_detail_1 = (p:any)=> <div>franchise 1 fees</div>;
export const franchise_detail_2 = (p:any)=> <div>franchise 2 FDD</div>;
export const franchise_detail_3 = (p:any)=> <div>franchise 3 territory</div>;
export const franchise_detail_4 = (p:any)=> <div>franchise 4 royalty 6%</div>;
export const franchise_detail_5 = (p:any)=> <div>franchise 5 fees</div>;
export const franchise_detail_6 = (p:any)=> <div>franchise 6 FDD</div>;
export const franchise_detail_7 = (p:any)=> <div>franchise 7 territory</div>;
export const franchise_detail_8 = (p:any)=> <div>franchise 8 royalty 6%</div>;
export const franchise_detail_9 = (p:any)=> <div>franchise 9 fees</div>;
export const franchise_detail_10 = (p:any)=> <div>franchise 10 FDD</div>;
export const franchise_detail_11 = (p:any)=> <div>franchise 11 territory</div>;
export const franchise_detail_12 = (p:any)=> <div>franchise 12 royalty 6%</div>;
export const franchise_detail_13 = (p:any)=> <div>franchise 13 fees</div>;
export const franchise_detail_14 = (p:any)=> <div>franchise 14 FDD</div>;
export const franchise_detail_15 = (p:any)=> <div>franchise 15 territory</div>;
export const franchise_detail_16 = (p:any)=> <div>franchise 16 royalty 6%</div>;
export const franchise_detail_17 = (p:any)=> <div>franchise 17 fees</div>;
export const franchise_detail_18 = (p:any)=> <div>franchise 18 FDD</div>;
export const franchise_detail_19 = (p:any)=> <div>franchise 19 territory</div>;